version: "3"
services:
  nginx:
    build: containers/nginx
    depends_on:
      - php_fpm
    volumes:
      - .:/var/app
    networks:
      default_network:
        aliases:
          - local.phpimagick.com
  php_fpm:
    build: containers/php_fpm
    environment:
      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_IDE_CONFIG= 'serverName=example.org'
    networks:
      default_network:
    volumes:
      - .:/var/app
networks:
  default_network:

